language: node_js

node_js:
  - lts/*
  - node

cache: npm

install:
  - npm ci

before_script:
  - npm run bootstrap

script:
  - npm run lint
  - npm run build
  - npm run test:unit -- --coverage
  - npm run test:integration

after_success:
  - npm install codecov -g
  - codecov
